name=YostLabs 3-Space Sensors
version=1.0.0
author=Yost Labs <techsupport@yostlabs.com>
maintainer=Andy Riedlinger <andy@yostlabs.com>
sentence=Driver for v3.0 Yost Labs 3-Space Sensors.
paragraph=Contains the communication library and other tools for working with V3 3-Space sensors.
category=Sensors
url=https://github.com/YostLabs/3Space-Arduino
architectures=*
includes=TSS.h
