name=TSS
version=1.0.0
author=Andy Riedlinger <techsupport@yostlabs.com>
maintainer=Andy Riedlinger <techsupport@yostlabs.com>
sentence=Driver for v3.0 Yostlabs Threespace Sensors.
paragraph=Contains the communication library and other tools for working with yostlabs v3 sensors.
category=Communication
url=https://github.com/YostLabs/3Space-Arduino
architectures=*
includes=TSS.h
